/**
 * MCP Resources
 * Define text-based resources for the server
 */

export const METHODOLOGY_RESOURCE = `# PROOFOF.ai 12-AI Democratic Voting Consensus Methodology

## Overview
PROOFOF.ai uses an ensemble of 12 specialized AI models to authenticate digital content through democratic consensus voting. This approach ensures robust detection of deepfakes and manipulated content across multiple modalities.

## The 12 AI Voters

1. **ResNet-50 Forensic Analyzer**
   - Specialization: Image and video forensics
   - Accuracy: 94%
   - Detects compression artifacts, lighting inconsistencies, and facial anomalies

2. **XceptionNet Deepfake Detector**
   - Specialization: Video and audio deepfakes
   - Accuracy: 92%
   - Identifies synthetic face generation and voice synthesis

3. **FaceSwap Detection Engine**
   - Specialization: Image and video face manipulation
   - Accuracy: 96%
   - Detects face-swap boundaries and blending artifacts

4. **Audio Splicing Detector**
   - Specialization: Audio content analysis
   - Accuracy: 91%
   - Identifies discontinuities in speech and unnatural prosody

5. **Metadata Analyzer**
   - Specialization: Image and document metadata
   - Accuracy: 88%
   - Detects tampering in EXIF, IPTC, and document properties

6. **Behavioral Pattern Recognition**
   - Specialization: Video and text behavior analysis
   - Accuracy: 89%
   - Analyzes human behavioral consistency and natural language patterns

7. **Frequency Domain Analyzer**
   - Specialization: Image and audio frequency analysis
   - Accuracy: 93%
   - Detects anomalies in frequency spectrums and Fourier transforms

8. **Neural Texture Detection**
   - Specialization: Image and video GAN-generated content
   - Accuracy: 95%
   - Identifies neural textures and synthetic rendering artifacts

9. **Optical Flow Analyzer**
   - Specialization: Video motion analysis
   - Accuracy: 90%
   - Detects unnatural motion patterns and inconsistencies

10. **Compression Artifact Analyzer**
    - Specialization: Image and video compression analysis
    - Accuracy: 87%
    - Identifies double compression and codec-specific artifacts

11. **GAN Detection Network**
    - Specialization: Generative AI detection
    - Accuracy: 94%
    - Detects content generated by GANs and diffusion models

12. **Ensemble Classifier**
    - Specialization: Multi-modal comprehensive analysis
    - Accuracy: 96%
    - Combines insights from other models for final consensus

## Voting Process

### Step 1: Content Ingestion
- Content is submitted for verification
- Content hash (SHA-256) is generated
- Initial metadata extraction occurs

### Step 2: Voter Selection
- Voters are selected based on content type specialization
- Typically 8-12 voters participate depending on content type
- Each voter is weighted by its accuracy score

### Step 3: Independent Analysis
- Each voter independently analyzes the content
- Detection indicators are accumulated
- Confidence scores are generated per voter

### Step 4: Consensus Vote
- Each voter casts a vote: AUTHENTIC, MANIPULATED, or UNCERTAIN
- Votes are weighted by voter accuracy
- A 67% supermajority threshold is required for consensus

### Step 5: Result Aggregation
- Consensus verdict is determined
- Authenticity score (0-100) is calculated
- Confidence level is established
- Detailed analysis is compiled

## Consensus Thresholds

- **AUTHENTIC**: ≥67% of weighted votes
- **MANIPULATED**: ≥67% of weighted votes for manipulation
- **UNCERTAIN**: When no consensus is reached (<67%)

## Authenticity Scoring

\`\`\`
Authenticity Score = (Authentic Votes / Total Votes) × Consensus Strength × (1 - Indicator Penalty)

Where:
- Authentic Votes = votes for authentic content
- Total Votes = number of participating voters
- Consensus Strength = 0-100 (67% = minimum consensus)
- Indicator Penalty = min(# of indicators × 0.1, 0.4)
\`\`\`

## Confidence Level Calculation

\`\`\`
Confidence = Consensus Strength - (Uncertain Votes / Total Votes) × 30

- High Confidence: ≥80
- Medium Confidence: 50-79
- Low Confidence: <50
\`\`\`

## Detection Methods

- **AI Voting Consensus**: Ensemble voting from specialized models
- **Forensic Analysis**: Pixel-level and frequency analysis
- **Blockchain Anchor**: Immutable verification records
- **Metadata Analysis**: File property verification
- **Behavioral Analysis**: Content pattern matching
- **Combined**: Multiple detection methods applied

## Accuracy & Performance

- Overall System Accuracy: 93.4%
- False Positive Rate: 2.1%
- False Negative Rate: 4.5%
- Average Processing Time: 15-45 seconds per content item
- Batch Processing: Up to 100 items per batch

## Supported Content Types

- **Images**: JPEG, PNG, WebP, BMP (up to 100MB)
- **Videos**: MP4, WebM, MOV (up to 500MB)
- **Audio**: MP3, WAV, AAC (up to 200MB)
- **Text**: Plain text documents (up to 1MB)
- **Documents**: PDF, DOCX (up to 50MB)

## Blockchain Anchoring

Verified results can be anchored to blockchain for immutability:
- Transaction ID: Unique blockchain reference
- Network: Ethereum, Polygon, or Bitcoin
- Timestamp: Precise verification moment
- QR Code: Easy verification link
- Smart Contract: Automated verification records
`;

export const SUPPORTED_FORMATS_RESOURCE = `# PROOFOF.ai Supported Content Formats

## Image Formats
- **JPEG/JPG**: Maximum 100MB, supports EXIF metadata
- **PNG**: Maximum 100MB, lossless compression support
- **WebP**: Maximum 100MB, modern format support
- **BMP**: Maximum 100MB, uncompressed bitmap
- **TIFF**: Maximum 100MB, tagged image format
- **GIF**: Maximum 100MB, animated sequence support

## Video Formats
- **MP4**: Maximum 500MB, H.264/H.265 codec support
- **WebM**: Maximum 500MB, VP8/VP9 codec support
- **MOV**: Maximum 500MB, Apple QuickTime format
- **AVI**: Maximum 500MB, legacy format support
- **MKV**: Maximum 500MB, Matroska container
- **FLV**: Maximum 500MB, Flash video format

## Audio Formats
- **MP3**: Maximum 200MB, MPEG Layer III
- **WAV**: Maximum 200MB, uncompressed PCM
- **AAC**: Maximum 200MB, advanced audio codec
- **FLAC**: Maximum 200MB, lossless compression
- **OGG**: Maximum 200MB, Vorbis codec
- **M4A**: Maximum 200MB, Apple audio format

## Text Formats
- **TXT**: Maximum 1MB, plain text
- **Markdown**: Maximum 1MB, .md files
- **JSON**: Maximum 1MB, structured text
- **XML**: Maximum 1MB, markup language
- **CSV**: Maximum 1MB, comma-separated values
- **HTML**: Maximum 1MB, web markup

## Document Formats
- **PDF**: Maximum 50MB, with OCR support
- **DOCX**: Maximum 50MB, Microsoft Word
- **DOC**: Maximum 50MB, legacy Word format
- **XLSX**: Maximum 50MB, Excel spreadsheets
- **PPTX**: Maximum 50MB, PowerPoint presentations
- **RTF**: Maximum 50MB, rich text format
- **ODF**: Maximum 50MB, OpenDocument formats

## Resolution & Quality Requirements

### Image Quality
- Minimum Resolution: 320x320 pixels
- Recommended Resolution: 1080x1080 or higher
- Color Depth: 8-bit or 16-bit per channel
- DPI: No specific requirement

### Video Quality
- Minimum Resolution: 480p (854x480)
- Recommended Resolution: 1080p or 4K
- Frame Rate: 24fps minimum
- Bitrate: Minimum 1Mbps

### Audio Quality
- Sample Rate: 44.1kHz minimum (96kHz recommended)
- Bit Depth: 16-bit minimum (24-bit recommended)
- Duration: Minimum 1 second

## Processing Limits

| Content Type | Max File Size | Max Duration | Rate Limit |
|---|---|---|---|
| Image | 100MB | N/A | 10/minute |
| Video | 500MB | 30 minutes | 5/minute |
| Audio | 200MB | 1 hour | 10/minute |
| Text | 1MB | N/A | 20/minute |
| Document | 50MB | N/A | 5/minute |

## Batch Processing

- **Maximum Items per Batch**: 100
- **Maximum Batch Size**: 5GB total
- **Processing Time**: Approximately 15 seconds per item
- **Parallel Processing**: Enabled by default
- **Rate Limiting**: 100 batches per hour

## Format-Specific Considerations

### Image Formats
- EXIF data is analyzed for tampering indicators
- Color profile mismatches are flagged
- Compression patterns are analyzed across format types

### Video Formats
- Frame-by-frame analysis is performed
- Audio track is separately analyzed
- Temporal inconsistencies are detected

### Audio Formats
- Frequency spectrum analysis
- Voice pattern recognition
- Splicing and editing detection

### Text Formats
- Stylometric analysis
- Plagiarism detection
- Semantic consistency checking

### Document Formats
- Metadata extraction and analysis
- Digital signature verification
- Version history analysis
- Embedded object scanning
`;

export const API_REFERENCE_RESOURCE = `# PROOFOF.ai MCP Server API Reference

## Server Information
- **Name**: proofof-ai-mcp
- **Version**: 1.0.0
- **Author**: PROOFOF.ai
- **License**: CC0-1.0
- **Homepage**: https://proofof.ai

## Tools

### 1. proofof_verify_content
Verify the authenticity of digital content using 12-AI democratic voting consensus.

**Input Parameters:**
\`\`\`json
{
  "contentUrl": "https://example.com/image.jpg",  // Optional
  "contentDescription": "Image showing alleged event at location",  // Required, 10-10000 chars
  "contentType": "image",  // Required: image|video|audio|text|document
  "sourceContext": "Posted on social media",  // Optional
  "performBlockchainAnchor": false  // Optional, default: false
}
\`\`\`

**Output:**
\`\`\`json
{
  "contentHash": "sha256_hash_string",
  "authenticityScore": 85,  // 0-100
  "confidenceLevel": 90,  // 0-100
  "detectionMethod": "ai-voting-consensus",
  "blockchainVerificationHash": "optional_hash",
  "verdict": "authentic",  // authentic|manipulated|uncertain
  "timestamp": "2024-01-15T10:30:00Z",
  "analysisDetails": {
    "manipulationIndicators": ["Indicator 1", "Indicator 2"],
    "aiVotingResults": {
      "consensusCount": 10,
      "totalVoters": 12,
      "agreementPercentage": 83
    },
    "forensicFindings": ["Finding 1", "Finding 2"]
  }
}
\`\`\`

### 2. proofof_deepfake_detect
Analyze content for deepfake indicators and AI-generated manipulation.

**Input Parameters:**
\`\`\`json
{
  "contentDescription": "Video showing person speaking",  // Required, 10-10000 chars
  "contentType": "video",  // Required: image|video|audio|text|document
  "sourceContext": "Viral video claiming authenticity",  // Optional
  "contentUrl": "https://example.com/video.mp4",  // Optional
  "advancedAnalysis": false  // Optional, default: false
}
\`\`\`

**Output:**
\`\`\`json
{
  "deepfakeProbability": 45,  // 0-100
  "manipulationIndicators": ["Indicator 1"],
  "aiModelsDetected": ["ResNet-50", "XceptionNet"],
  "riskLevel": "medium",  // low|medium|high|critical
  "recommendedActions": [
    "Add content warning",
    "Request source verification"
  ],
  "timestamp": "2024-01-15T10:30:00Z",
  "confidenceScore": 78  // 0-100
}
\`\`\`

### 3. proofof_blockchain_anchor
Anchor verification results to blockchain for immutability.

**Input Parameters:**
\`\`\`json
{
  "verificationResultHash": "sha256_hash_of_verification",  // Required
  "contentHash": "sha256_hash_of_content",  // Required
  "blockchainNetwork": "ethereum",  // Optional: ethereum|polygon|bitcoin
  "metadata": { "key": "value" }  // Optional
}
\`\`\`

**Output:**
\`\`\`json
{
  "transactionId": "0x...",
  "blockchainNetwork": "ethereum",
  "timestamp": "2024-01-15T10:30:00Z",
  "immutableRecord": {
    "contentHash": "...",
    "verificationResult": { /* full result */ },
    "anchordTimestamp": "2024-01-15T10:30:00Z"
  },
  "qrCodeData": "data:application/json;base64,..."
}
\`\`\`

### 4. proofof_credential_issue
Issue W3C verifiable credentials for content verification.

**Input Parameters:**
\`\`\`json
{
  "contentHash": "sha256_hash",  // Required
  "verificationResultHash": "sha256_hash",  // Required
  "recipientEmail": "user@example.com",  // Optional
  "recipientName": "John Doe",  // Optional
  "publisherName": "News Agency",  // Optional
  "issueLinkedInBadge": false  // Optional, default: false
}
\`\`\`

**Output:**
\`\`\`json
{
  "@context": ["https://www.w3.org/2018/credentials/v1"],
  "type": ["VerifiableCredential", "ContentVerificationCredential"],
  "issuer": {
    "id": "https://proofof.ai",
    "name": "PROOFOF.ai"
  },
  "issuanceDate": "2024-01-15T10:30:00Z",
  "credentialSubject": {
    "id": "mailto:user@example.com",
    "contentHash": "...",
    "verificationResult": { /* verification details */ }
  },
  "proof": { /* cryptographic proof */ },
  "linkedInBadgeUrl": "https://www.credly.com/badges/...",
  "qrCode": "data:image/png;base64,..."
}
\`\`\`

### 5. proofof_batch_verify
Verify multiple content items in a single batch request.

**Input Parameters:**
\`\`\`json
{
  "items": [
    {
      "contentUrl": "url",  // Optional
      "contentDescription": "description",  // Required
      "contentType": "image"  // Required
    }
  ],  // Min 1, Max 100 items
  "performBlockchainAnchor": false,  // Optional
  "parallelProcessing": true  // Optional, default: true
}
\`\`\`

**Output:**
\`\`\`json
{
  "items": [
    {
      "index": 0,
      "result": { /* VerificationResult */ },
      "status": "success"
    }
  ],
  "summary": {
    "totalProcessed": 5,
    "successful": 5,
    "failed": 0,
    "averageAuthenticityScore": 82,
    "verdictDistribution": {
      "authentic": 3,
      "manipulated": 1,
      "uncertain": 1
    }
  },
  "timestamp": "2024-01-15T10:30:00Z"
}
\`\`\`

### 6. proofof_trust_score
Calculate trust score for content sources and publishers.

**Input Parameters:**
\`\`\`json
{
  "sourceUrl": "https://news.example.com",  // Optional
  "publisherName": "Major News Network",  // Optional
  "includeReputation": true,  // Optional, default: true
  "includeHistory": true  // Optional, default: true
}
\`\`\`

**Output:**
\`\`\`json
{
  "sourceUrl": "https://news.example.com",
  "publisherName": "Major News Network",
  "trustScore": 87,  // 0-100
  "reliabilityMetrics": {
    "verificationHistory": {
      "total": 1500,
      "authentic": 1425,
      "manipulated": 45,
      "uncertain": 30
    },
    "authenticityRate": 95,
    "consistencyScore": 92,
    "reportedViolations": 0
  },
  "riskLevel": "low",  // low|medium|high
  "reputation": {
    "endorsements": 45,
    "disputes": 5,
    "correctionsMade": 3
  },
  "lastUpdated": "2024-01-15T10:30:00Z"
}
\`\`\`

## Response Codes

| Code | Status | Description |
|---|---|---|
| 200 | Success | Tool executed successfully |
| 400 | Bad Request | Invalid input parameters |
| 429 | Rate Limited | Too many requests |
| 500 | Server Error | Internal processing error |

## Rate Limits

- Standard Tier: 100 requests per minute
- Batch Mode: 10 batches per minute
- Burst: Up to 500 requests per day

## Authentication

All API calls include tool-level authentication through the MCP protocol. No separate API keys required.

## Best Practices

1. Always provide comprehensive content descriptions
2. Use batch verification for multiple items
3. Anchor critical verifications to blockchain
4. Check trust scores for source reliability
5. Monitor confidence levels for verification accuracy
6. Use advanced analysis for uncertain results
7. Keep verification records for audit trails
`;
